// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuctionNodeService_Announce_FullMethodName       = "/AuctionNodeService/Announce"
	AuctionNodeService_GetNodes_FullMethodName       = "/AuctionNodeService/GetNodes"
	AuctionNodeService_Ready_FullMethodName          = "/AuctionNodeService/Ready"
	AuctionNodeService_Election_FullMethodName       = "/AuctionNodeService/Election"
	AuctionNodeService_Coordinator_FullMethodName    = "/AuctionNodeService/Coordinator"
	AuctionNodeService_GetCoordinator_FullMethodName = "/AuctionNodeService/GetCoordinator"
	AuctionNodeService_SendBid_FullMethodName        = "/AuctionNodeService/SendBid"
	AuctionNodeService_GetResult_FullMethodName      = "/AuctionNodeService/GetResult"
	AuctionNodeService_SendUpdate_FullMethodName     = "/AuctionNodeService/SendUpdate"
	AuctionNodeService_Ping_FullMethodName           = "/AuctionNodeService/Ping"
)

// AuctionNodeServiceClient is the client API for AuctionNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionNodeServiceClient interface {
	// Service discovery
	Announce(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Empty, error)
	GetNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Nodes, error)
	Ready(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// The bully
	Election(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Coordinator(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
	GetCoordinator(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Request, error)
	// Auction
	SendBid(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*Ack, error)
	GetResult(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error)
	// Replication
	SendUpdate(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Empty, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type auctionNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionNodeServiceClient(cc grpc.ClientConnInterface) AuctionNodeServiceClient {
	return &auctionNodeServiceClient{cc}
}

func (c *auctionNodeServiceClient) Announce(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AuctionNodeService_Announce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) GetNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Nodes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nodes)
	err := c.cc.Invoke(ctx, AuctionNodeService_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) Ready(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AuctionNodeService_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) Election(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AuctionNodeService_Election_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) Coordinator(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AuctionNodeService_Coordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) GetCoordinator(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, AuctionNodeService_GetCoordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) SendBid(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AuctionNodeService_SendBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) GetResult(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, AuctionNodeService_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) SendUpdate(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AuctionNodeService_SendUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AuctionNodeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionNodeServiceServer is the server API for AuctionNodeService service.
// All implementations must embed UnimplementedAuctionNodeServiceServer
// for forward compatibility.
type AuctionNodeServiceServer interface {
	// Service discovery
	Announce(context.Context, *Node) (*Empty, error)
	GetNodes(context.Context, *Empty) (*Nodes, error)
	Ready(context.Context, *Empty) (*Empty, error)
	// The bully
	Election(context.Context, *Empty) (*Empty, error)
	Coordinator(context.Context, *Request) (*Empty, error)
	GetCoordinator(context.Context, *Empty) (*Request, error)
	// Auction
	SendBid(context.Context, *Bid) (*Ack, error)
	GetResult(context.Context, *Empty) (*Result, error)
	// Replication
	SendUpdate(context.Context, *Update) (*Empty, error)
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedAuctionNodeServiceServer()
}

// UnimplementedAuctionNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctionNodeServiceServer struct{}

func (UnimplementedAuctionNodeServiceServer) Announce(context.Context, *Node) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Announce not implemented")
}
func (UnimplementedAuctionNodeServiceServer) GetNodes(context.Context, *Empty) (*Nodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedAuctionNodeServiceServer) Ready(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedAuctionNodeServiceServer) Election(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Election not implemented")
}
func (UnimplementedAuctionNodeServiceServer) Coordinator(context.Context, *Request) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Coordinator not implemented")
}
func (UnimplementedAuctionNodeServiceServer) GetCoordinator(context.Context, *Empty) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoordinator not implemented")
}
func (UnimplementedAuctionNodeServiceServer) SendBid(context.Context, *Bid) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBid not implemented")
}
func (UnimplementedAuctionNodeServiceServer) GetResult(context.Context, *Empty) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedAuctionNodeServiceServer) SendUpdate(context.Context, *Update) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUpdate not implemented")
}
func (UnimplementedAuctionNodeServiceServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAuctionNodeServiceServer) mustEmbedUnimplementedAuctionNodeServiceServer() {}
func (UnimplementedAuctionNodeServiceServer) testEmbeddedByValue()                            {}

// UnsafeAuctionNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionNodeServiceServer will
// result in compilation errors.
type UnsafeAuctionNodeServiceServer interface {
	mustEmbedUnimplementedAuctionNodeServiceServer()
}

func RegisterAuctionNodeServiceServer(s grpc.ServiceRegistrar, srv AuctionNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuctionNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuctionNodeService_ServiceDesc, srv)
}

func _AuctionNodeService_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_Announce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).Announce(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).GetNodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).Ready(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_Election_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).Election(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_Election_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).Election(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_Coordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).Coordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_Coordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).Coordinator(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_GetCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).GetCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_GetCoordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).GetCoordinator(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_SendBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).SendBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_SendBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).SendBid(ctx, req.(*Bid))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).GetResult(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_SendUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Update)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).SendUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_SendUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).SendUpdate(ctx, req.(*Update))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNodeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionNodeService_ServiceDesc is the grpc.ServiceDesc for AuctionNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuctionNodeService",
	HandlerType: (*AuctionNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Announce",
			Handler:    _AuctionNodeService_Announce_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _AuctionNodeService_GetNodes_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _AuctionNodeService_Ready_Handler,
		},
		{
			MethodName: "Election",
			Handler:    _AuctionNodeService_Election_Handler,
		},
		{
			MethodName: "Coordinator",
			Handler:    _AuctionNodeService_Coordinator_Handler,
		},
		{
			MethodName: "GetCoordinator",
			Handler:    _AuctionNodeService_GetCoordinator_Handler,
		},
		{
			MethodName: "SendBid",
			Handler:    _AuctionNodeService_SendBid_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _AuctionNodeService_GetResult_Handler,
		},
		{
			MethodName: "SendUpdate",
			Handler:    _AuctionNodeService_SendUpdate_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AuctionNodeService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
