// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bidding
type State int32

const (
	State_SUCCESS   State = 0
	State_FAIL      State = 1
	State_EXCEPTION State = 2
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
		2: "EXCEPTION",
	}
	State_value = map[string]int32{
		"SUCCESS":   0,
		"FAIL":      1,
		"EXCEPTION": 2,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

// For service discovery
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,67,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Nodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          []int32                `protobuf:"varint,6767,rep,packed,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nodes) Reset() {
	*x = Nodes{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nodes) ProtoMessage() {}

func (x *Nodes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nodes.ProtoReflect.Descriptor instead.
func (*Nodes) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Nodes) GetPort() []int32 {
	if x != nil {
		return x.Port
	}
	return nil
}

// Elections
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,676767,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Bid) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bid) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,3,opt,name=state,proto3,enum=State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetState() State {
	if x != nil {
		return x.State
	}
	return State_SUCCESS
}

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int32                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Amount        int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	BidderName    string                 `protobuf:"bytes,6,opt,name=bidder_name,json=bidderName,proto3" json:"bidder_name,omitempty"`
	Done          bool                   `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{6}
}

func (x *Update) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Update) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Update) GetBidderName() string {
	if x != nil {
		return x.BidderName
	}
	return ""
}

func (x *Update) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,8,opt,name=done,proto3" json:"done,omitempty"`
	Winner        string                 `protobuf:"bytes,9,opt,name=winner,proto3" json:"winner,omitempty"`
	HighestBid    int32                  `protobuf:"varint,10,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{7}
}

func (x *Result) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Result) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *Result) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"\a\n" +
	"\x05Empty\"\x1a\n" +
	"\x04Node\x12\x12\n" +
	"\x04port\x18C \x01(\x05R\x04port\"\x1c\n" +
	"\x05Nodes\x12\x13\n" +
	"\x04port\x18\xef4 \x03(\x05R\x04port\"\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x04port\x18\x9f\xa7) \x01(\x05R\x04port\"1\n" +
	"\x03Bid\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"#\n" +
	"\x03Ack\x12\x1c\n" +
	"\x05state\x18\x03 \x01(\x0e2\x06.StateR\x05state\"s\n" +
	"\x06Update\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x05R\ttimestamp\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12\x1f\n" +
	"\vbidder_name\x18\x06 \x01(\tR\n" +
	"bidderName\x12\x12\n" +
	"\x04done\x18\a \x01(\bR\x04done\"U\n" +
	"\x06Result\x12\x12\n" +
	"\x04done\x18\b \x01(\bR\x04done\x12\x16\n" +
	"\x06winner\x18\t \x01(\tR\x06winner\x12\x1f\n" +
	"\vhighest_bid\x18\n" +
	" \x01(\x05R\n" +
	"highestBid*-\n" +
	"\x05State\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x022\xc5\x02\n" +
	"\x12AuctionNodeService\x12\x1b\n" +
	"\bAnnounce\x12\x05.Node\x1a\x06.Empty\"\x00\x12\x1c\n" +
	"\bGetNodes\x12\x06.Empty\x1a\x06.Nodes\"\x00\x12\x19\n" +
	"\x05Ready\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x1c\n" +
	"\bElection\x12\x06.Empty\x1a\x06.Empty\"\x00\x12!\n" +
	"\vCoordinator\x12\b.Request\x1a\x06.Empty\"\x00\x12$\n" +
	"\x0eGetCoordinator\x12\x06.Empty\x1a\b.Request\"\x00\x12\x17\n" +
	"\aSendBid\x12\x04.Bid\x1a\x04.Ack\"\x00\x12\x1e\n" +
	"\tGetResult\x12\x06.Empty\x1a\a.Result\"\x00\x12\x1f\n" +
	"\n" +
	"SendUpdate\x12\a.Update\x1a\x06.Empty\"\x00\x12\x18\n" +
	"\x04Ping\x12\x06.Empty\x1a\x06.Empty\"\x00B\x14Z\x12Auction/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_proto_goTypes = []any{
	(State)(0),      // 0: State
	(*Empty)(nil),   // 1: Empty
	(*Node)(nil),    // 2: Node
	(*Nodes)(nil),   // 3: Nodes
	(*Request)(nil), // 4: Request
	(*Bid)(nil),     // 5: Bid
	(*Ack)(nil),     // 6: Ack
	(*Update)(nil),  // 7: Update
	(*Result)(nil),  // 8: Result
}
var file_proto_proto_depIdxs = []int32{
	0,  // 0: Ack.state:type_name -> State
	2,  // 1: AuctionNodeService.Announce:input_type -> Node
	1,  // 2: AuctionNodeService.GetNodes:input_type -> Empty
	1,  // 3: AuctionNodeService.Ready:input_type -> Empty
	1,  // 4: AuctionNodeService.Election:input_type -> Empty
	4,  // 5: AuctionNodeService.Coordinator:input_type -> Request
	1,  // 6: AuctionNodeService.GetCoordinator:input_type -> Empty
	5,  // 7: AuctionNodeService.SendBid:input_type -> Bid
	1,  // 8: AuctionNodeService.GetResult:input_type -> Empty
	7,  // 9: AuctionNodeService.SendUpdate:input_type -> Update
	1,  // 10: AuctionNodeService.Ping:input_type -> Empty
	1,  // 11: AuctionNodeService.Announce:output_type -> Empty
	3,  // 12: AuctionNodeService.GetNodes:output_type -> Nodes
	1,  // 13: AuctionNodeService.Ready:output_type -> Empty
	1,  // 14: AuctionNodeService.Election:output_type -> Empty
	1,  // 15: AuctionNodeService.Coordinator:output_type -> Empty
	4,  // 16: AuctionNodeService.GetCoordinator:output_type -> Request
	6,  // 17: AuctionNodeService.SendBid:output_type -> Ack
	8,  // 18: AuctionNodeService.GetResult:output_type -> Result
	1,  // 19: AuctionNodeService.SendUpdate:output_type -> Empty
	1,  // 20: AuctionNodeService.Ping:output_type -> Empty
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
